name: Build USB Serial APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: usb-serial-debug-apk
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: usb-serial-release-apk
        path: app/build/outputs/apk/release/*.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: USB Serial App v1.0.${{ github.run_number }}
        body: |
          🚀 **USB Serial Communication App**
          
          ## ✅ Funcionalidades:
          - Comunicação USB-Serial (Arduino, CH340, FTDI, etc.)
          - Interface de terminal em tempo real
          - Detecção automática de dispositivos
          - Envio de comandos personalizados
          - Logs detalhados para diagnóstico
          
          ## 📱 Downloads:
          - **Debug APK**: Para desenvolvimento e testes
          - **Release APK**: Para uso em produção
          
          ## 🔧 Dispositivos suportados:
          - Arduino (VID: 0x2341)
          - CH340/CH341 (VID: 0x1A86)
          - FTDI (VID: 0x0403)
          - Silicon Labs CP210x (VID: 0x10C4)
          - Prolific PL2303 (VID: 0x067B)
          - CDC Communication devices
        draft: false
        prerelease: false 